run/core/controllers/login.py
#!/usr/bin/env python3


from flask import Blueprint, redirect, render_template, request, session, url_for

from core.models import model


controller = Blueprint("login", __name__, url_prefix="/login")

@controller.route("/", methods=["GET", "POST"])
def show_login():
	# In session (user signed in)
	if "username" in session:
		return redirect(url_for("main.show_main"))
	# Out of session (user not signed in)
	else:
		# GET request
		if request.method == "GET":
			return render_template("login.html")
		# POST request
		else:
			# Accesses current form data (data transmitted in a POST request).
			username = request.form["username"]
			password = request.form["password"]
			# Attempts to log in to the account with the entered username and password.
			response = model.login(username, password)
			# If the user has successfully logged in to their account.
			if "Success" in response:
				session["username"] = username
				session["first_name"], session["last_name"] = model.get_name(username)
				# If it is the admin user.
				if "Admin" in response:
					# TODO: Add admin functionality.
					return redirect(url_for("main.show_main"))
				# If it is any other user.
				else:
					return redirect(url_for("main.show_main"))
			# If there was an issue with logging in to the account (username or account does not exist).
			else:
				return render_template("login.html", response=response)

run/core/controllers/main.py
#!/usr/bin/env python3


from flask import abort, Blueprint, redirect, render_template, request, session, url_for

from core.models import model


controller = Blueprint("main", __name__, url_prefix="/")

# Shows the feed page (if user is in session), or the signup page (if user is not in session).
@controller.route("/", methods=["GET", "POST"])
def show_main():
	# Feed page (in session - user signed in)
	if "username" in session:
		# GET request
		if request.method == "GET":
			return render_template("feed.html", \
									username=session["username"], \
									first_name=session["first_name"], \
									last_name=session["last_name"],
									num_posts=model.get_num_posts(session["username"]), \
									num_reposts=model.get_num_reposts(session["username"]), \
									posts=model.get_all_posts(), \
									reposts=model.get_reposts(session["username"]), \
									title="Feed")
		# POST request
		else:
			# Clicking post button.
			if "post-button" in request.form:
				content = request.form["content"]
				# If the post is greater than 280 characters or has 0 characters (it is invalid).
				if len(content) > 280 or len(content) == 0:
					return render_template("feed.html", \
										username=session["username"], \
										first_name=session["first_name"], \
										last_name=session["last_name"],
										num_posts=model.get_num_posts(session["username"]), \
										num_reposts=model.get_num_reposts(session["username"]), \
										posts=model.get_all_posts(), \
										reposts=model.get_reposts(session["username"]), \
										content=content, \
										error="e", \
										title="Feed")
				# If the post is fewer than 280 characters (it is valid).
				else:
					model.add_new_post(session["username"], content)
					return render_template("feed.html", \
											username=session["username"], \
											first_name=session["first_name"], \
											last_name=session["last_name"],
											num_posts=model.get_num_posts(session["username"]), \
											num_reposts=model.get_num_reposts(session["username"]), \
											posts=model.get_all_posts(), \
											reposts=model.get_reposts(session["username"]), \
											title="Feed")
			# Clicking repost button.
			elif "repost-button" in request.form:
				post_id = request.form["post-id"]
				model.add_new_repost(session["username"], post_id)
				return render_template("feed.html", \
											username=session["username"], \
											first_name=session["first_name"], \
											last_name=session["last_name"],
											num_posts=model.get_num_posts(session["username"]), \
											num_reposts=model.get_num_reposts(session["username"]), \
											posts=model.get_all_posts(), \
											reposts=model.get_reposts(session["username"]), \
											title="Feed")
	# Signup page (out of session - user not signed in)
	else:
		# GET request
		if request.method == "GET":
			return render_template("signup.html")
		# POST request
		else:
			# Accesses current form data (data transmitted in a POST request).
			username = request.form["username"]
			first_name = request.form["first-name"]
			last_name = request.form["last-name"]
			password1 = request.form["password1"]
			password2 = request.form["password2"]
			# If the passwords the user entered match.
			if password1 == password2:
				# Attempts to create an account with the entered username and password.
				response = model.create_account(username, password1, first_name, last_name)
				# If the user's account has been successfully created.
				if "Success" in response:
					session["username"] = username
					session["first_name"] = first_name
					session["last_name"] = last_name
					return render_template("feed.html", \
											username=username, \
											first_name=first_name, \
											last_name=last_name, \
											num_posts=model.get_num_posts(session["username"]), \
											num_reposts=model.get_num_reposts(session["username"]), \
											posts=model.get_all_posts(), \
											title="Feed")
				# If there was an issue creating the account (username already exists, account already exists, or username was invalid).
				else:
					return render_template("signup.html", response=response)
			# If the passowrds the user entered do not match.
			else:
				return render_template("signup.html", response=["Passwords did not match."])

# Handles signing out the user and removing them from the session.
@controller.route("/signout", methods=["GET"])
def signout():
	# In session (user signed in)
	if "username" in session:
		session.pop("username", None)
		session.pop("first_name", None)
		session.pop("last_name", None)
		return redirect(url_for("main.show_main"))
	# Out of session (user not signed in)
	else:
		return redirect(url_for("main.show_main"))

@controller.route("/base", methods=["GET"])
def show_base():
	return render_template("base.html", \
								username=session["username"], \
								first_name=session["first_name"], \
								last_name=session["last_name"],
								num_posts=model.get_num_posts(session["username"]), \
								num_reposts=model.get_num_reposts(session["username"]), \
								posts=model.get_all_posts(), \
								title="Base")

# Handles page requests for non-existent pages (404 errors).
@controller.route("/<path:path>", methods=["GET"])
def show_404(path):
	if "username" in session:
		return redirect(url_for("main.show_main"))
	else:
		abort(404)

@controller.errorhandler(404)
def page_not_found(e):
	return render_template("404.html"), 404

run/core/controllers/profile.py
#!/usr/bin/env python3


from flask import abort, Blueprint, redirect, render_template, request, session, url_for

from core.models import model


controller = Blueprint("profile", __name__, url_prefix="/profile")

@controller.route("/", methods=["GET"])
def show_profile():
    # In session (user signed in)
    if "username" in session:
        return render_template("profile.html", \
                                username=session["username"], \
                                first_name=session["first_name"], \
                                last_name=session["last_name"], \
                                num_posts=model.get_num_posts(session["username"]), \
								num_reposts=model.get_num_reposts(session["username"]), \
                                posts=model.get_posts(session["username"]), \
                                reposts=model.get_reposts(session["username"]), \
                                title="Profile")
    # Out of session (user not signed in)
    else:
        return redirect(url_for("main.show_main"))

run/core/controllers/signup.py
#!/usr/bin/env python3


from flask import abort, Blueprint, redirect, render_template, request, session, url_for

from core.models import model


controller = Blueprint("signup", __name__, url_prefix="/")

@controller.route("/", methods=["GET", "POST"])
def show_signup():
	# In session (user signed in)
	if "username" in session:
		return redirect(url_for("dashboard.show_dashboard"))
	# Out of session (user not signed in)
	else:
		# GET request
		if request.method == "GET":
			return render_template("signup.html")
		# POST request
		else:
			# Accesses current form data (data transmitted in a POST request).
			username = request.form["username"]
			password1 = request.form["password1"]
			password2 = request.form["password2"]
			# If the passwords the user entered match.
			if password1 == password2:
				# Attempts to create an account with the entered username and password.
				response = model.create_account(username, password1)
				# If the user's account has been successfully created.
				if "Success" in response:
					session["username"] = username
					return redirect(url_for("dashboard.show_dashboard"))
				# If there was an issue creating the account (username already exists, account already exists, or username was invalid).
				else:
					return render_template("signup.html", response=response)
			# If the passowrds the user entered do not match.
			else:
				return render_template("signup.html", response=["Passwords did not match."])

# Handles page requests for non-existent pages (404 errors).
@controller.route("/<path:path>", methods=["GET"])
def show_404(path):
	if "username" in session:
		return redirect(url_for("dashboard.show_dashboard"))
	else:
		abort(404)

@controller.errorhandler(404)
def page_not_found(e):
	return render_template("404.html"), 404

run/core/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">

    <title>TweetTweet - {{ username }}'s {{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="../static/base-styles.css" rel="stylesheet">
</head>

<body class="bg-light">
    <!-- Navbar. -->
    <nav class="navbar navbar-expand-lg fixed-top navbar-dark bg-dark">
        <!--<a class="navbar-brand mr-auto mr-lg-0" href="">TweetTweet</a>-->
        <a href="{{ url_for('main.show_main') }}"><img class="mr-3" src="{{ url_for('static', filename='tweettweet-icon.png') }}" alt="" width="40" height="40"></a>
        <button class="navbar-toggler p-0 border-0" type="button" data-toggle="offcanvas">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav mr-auto">
                {% if title == "Feed" %}
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('main.show_main') }}">Feed
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('main.show_main') }}">Feed</a>
                </li>
                {% endif %}
                {% if title == "Profile" %}
                <li class="nav-item active">
                    <a class="nav-link" href="{{ url_for('profile.show_profile') }}">Profile
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('profile.show_profile') }}">Profile</a>
                </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="" id="dropdown01" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">About</a>
                    <div class="dropdown-menu" aria-labelledby="dropdown01">
                        <a class="dropdown-item" href="http://www.matthewmuccio.com/" target="_blank">Matthew Muccio</a>
                        <a class="dropdown-item" href="https://github.com/matthewmuccio/Assessment2" target="_blank">Project</a>
                        <a class="dropdown-item" href="https://github.com/matthewmuccio" target="_blank">GitHub</a>
                        <a class="dropdown-item" href="https://www.linkedin.com/in/matthewmuccio/" target="_blank">LinkedIn</a>
                    </div>
                </li>
                <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.signout') }}">Sign out</a>
                    </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>

    <div class="nav-scroller bg-white box-shadow">
        <nav class="nav nav-underline">
            <a class="nav-link active" href="{{ url_for('profile.show_profile') }}">{{ first_name }} {{ last_name }}</a>
            <a class="nav-link" href="{{ url_for('profile.show_profile') }}">
                Posts
                <span class="badge badge-pill bg-light align-text-bottom">{{ num_posts }}</span>
            </a>
            <a class="nav-link" href="{{ url_for('profile.show_profile') }}">
                Reposts
                <span class="badge badge-pill bg-light align-text-bottom">{{ num_reposts }}</span>
            </a>
        </nav>
    </div>
    <!-- End navbar. -->

    {% block content %}
    {% endblock %}

    <!-- Footer. -->
    <footer class="py-5 bg-dark" style="margin-top: 50px; position: sticky; bottom: 0; left: 0; right: 0;">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Matthew Muccio 2018</p>
        </div>
    </footer>
    <!-- End footer. -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script>
        window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')
    </script>
    <script src="https://getbootstrap.com/docs/4.1/assets/js/vendor/popper.min.js"></script>
    <script src="https://getbootstrap.com/docs/4.1/dist/js/bootstrap.min.js"></script>
    <script src="https://getbootstrap.com/docs/4.1/assets/js/vendor/holder.min.js"></script>
    <script src="https://getbootstrap.com/docs/4.1/examples/offcanvas/offcanvas.js"></script>
</body>

</html>

run/core/templates/feed.html
{% extends "base.html" %}

{% block content %}
    <main role="main" class="container">
        <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-blue rounded box-shadow">
            <img class="mr-3" src="{{ url_for('static', filename='default-profile-pic.png') }}" alt="" width="80" height="80">
            <div class="lh-100">
                <h6 class="mb-0 text-white lh-100"><a href="{{ url_for('profile.show_profile') }}" class="no-link">{{ first_name }} {{ last_name }}</a></h6>
                <small class="mb-0 text-white lh-100">@<a href="{{ url_for('profile.show_profile') }}" class="no-link">{{ username }}</a></small>
            </div>

            <div class="justify-content-center">
                <form class="form-inline my-2 my-lg-0" style="padding-left: 150px;" id="textarea" method="POST">
                    <textarea name="content" id="post-textarea" style="-webkit-border-radius: 5px; -moz-border-radius: 5px; border-radius: 5px" cols="50" rows="3" placeholder="Tweet tweet!">{{ content }}</textarea>
                    <button name="post-button" value="Post" class="btn btn-light my-2 my-sm-0" style="margin-left: 20px;" type="submit">Post</button>
                </form>
                {% if error %}
                    <script>alert("Sorry, posts must contain between 1 and 280 characters.")</script>
                {% endif %}
            </div>
        </div>

        <div class="my-3 p-3 bg-white rounded box-shadow">
            <h6 class="border-bottom border-gray pb-2 mb-0">All Posts</h6>
            {% if posts %}
            {% for post_id, post_info in posts.items() %}
                <div class="media text-muted pt-3">
                    <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
                    <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <strong class="d-block text-gray-dark">{{ post_info[1] }} {{ post_info[2] }} (@{{ post_info[0] }}) · {{ post_info[4] }}</strong>
                        {{ post_info[3] }}
                    </p>
                    {% if post_info[0] != username and post_id not in reposts %}
                    <form method="POST">
                        <input name="post-id" type="hidden" value="{{ post_id }}">
                        <button name="repost-button" value="Repost" class="btn btn-info my-2 my-sm-0" style="margin-left: 20px;" type="submit">Repost</button>
                    </form>
                    {% endif %}
                </div>
            {% endfor %}
            {% endif %}
            <small class="d-block text-right mt-3">
                <a href="">Refresh</a>
            </small>
        </div>
    </main>
{% endblock %}

run/core/templates/login.html
<!DOCTYPE html>
<!-- https://getbootstrap.com/docs/4.1/examples/sign-in/ -->
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">

    <title>TweetTweet - Log In</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for the login template. -->
    <link href="{{ url_for('static', filename='login-styles.css') }}" rel="stylesheet">
</head>

<body class="text-center">
    <form class="form-signin" method="POST">
        <img class="mb-4" src="{{ url_for('static', filename='tweettweet-icon.png') }}" alt="" width="75" height="75">
        <h1 class="mb-4">TweetTweet</h1>
        {% if response %}
        <div style="margin-top: -8px; padding-bottom: 8px; line-height: 6px;">
        {% for line in response %}
            <p style="font-size: 12px; color: red;">{{ line }}</p>
        {% endfor %}
        </div>
        {% endif %}
        
        <label for="inputEmail" class="sr-only">Username</label>
        <input name="username" type="text" id="inputEmail" class="form-control" placeholder="Username" required autofocus>
        
        <label for="inputPassword" class="sr-only">Password</label>
        <input name="password" type="password" id="inputPassword" class="form-control" placeholder="Password" required>
        
        <div class="checkbox mb-3 text-center">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>

        <button class="btn btn-lg btn-success btn-block" type="submit">Log In</button>
        
        <div class="signup-button">
            <div class="text-center">
                <label>Don't have an account?</label>
            </div>
            <a href="{{ url_for('main.show_main') }}">
                <button class="btn btn-lg btn-info btn-block" type="button">Sign Up</button>
            </a>
        </div>

        <p class="mt-5 mb-3 text-muted">Copyright &copy; Matthew Muccio 2018</p>
    </form>
</body>

</html>

run/core/templates/profile.html
{% extends "base.html" %}

{% block content %}
    <main role="main" class="container">
        <div class="d-flex align-items-center p-3 my-3 text-white-50 bg-purple rounded box-shadow">
            <img class="mr-3" src="{{ url_for('static', filename='default-profile-pic.png') }}" alt="" width="80" height="80">
            <div class="lh-100">
                <h6 class="mb-0 text-white lh-100"><a href="{{ url_for('profile.show_profile') }}" class="no-link">{{ first_name }} {{ last_name }}</a></h6>
                <small class="mb-0 text-white lh-100">@<a href="{{ url_for('profile.show_profile') }}" class="no-link">{{ username }}</a></small>
            </div>
        </div>

        <div class="my-3 p-3 bg-white rounded box-shadow">
            <h6 class="border-bottom border-gray pb-2 mb-0">Your Posts ({{num_posts}})</h6>
            {% if posts %}
            {% for post_id, post_info in posts.items() %}
            <div class="media text-muted pt-3">
                <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
                <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                <strong class="d-block text-gray-dark">{{ first_name }} {{ last_name }} (@{{ username }}) · {{ post_info[1] }}</strong>
                    {{ post_info[0] }}
                </p>
            </div>
            {% endfor %}
            {% endif %}
            <small class="d-block text-right mt-3">
                <a href="">Refresh</a>
            </small>
        </div>

        <div class="my-3 p-3 bg-white rounded box-shadow">
            <h6 class="border-bottom border-gray pb-2 mb-0">Your Reposts ({{ num_reposts }})</h6>
            {% if reposts %}
            {% for post_id, post_info in reposts.items() %}
            <div class="media text-muted pt-3">
                <img data-src="holder.js/32x32?theme=thumb&bg=007bff&fg=007bff&size=1" alt="" class="mr-2 rounded">
                <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                <strong class="d-block text-gray-dark">{{ post_info[1] }} {{ post_info[2] }} (@{{ post_info[0] }}) · {{ post_info[4] }}</strong>
                    {{ post_info[3] }}
                </p>
            </div>
            {% endfor %}
            {% endif %}
            <small class="d-block text-right mt-3">
                <a href="">Refresh</a>
            </small>
        </div>
    </main>
{% endblock %}

run/core/templates/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">

    <title>TweetTweet - Sign Up</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.1/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for the signup template. -->
    <link href="{{ url_for('static', filename='signup-styles.css') }}" rel="stylesheet">
</head>

<body>
    <form class="form-signin" method="POST">
        <div class="text-center mb-4">
            <img class="mb-4" src="{{ url_for('static', filename='tweettweet-icon.png') }}" alt="" width="75" height="75">
            <h1 class="h3 mb-3">TweetTweet</h1>
            <p>A simple Twitter-like web application, for posting and reposting tweets from fellow users around the world.</p>
            {% if response %}
            <div style="line-height: 6px;">
            {% for line in response %}
                <p style="font-size: 12px; color: red;">{{ line }}</p>
            {% endfor %}
            </div>
            {% endif %}
        </div>

        <div class="form-label-group">
            <input name="first-name" type="text" id="inputFirstName" class="form-control" placeholder="First Name" required autofocus>
            <label for="inputFirstName">First Name</label>
        </div>

        <div class="form-label-group">
            <input name="last-name" type="text" id="inputLastName" class="form-control" placeholder="Last Name" required>
            <label for="inputLastName">Last Name</label>
        </div>

        <div class="form-label-group">
            <input name="username" type="text" id="inputEmail" class="form-control" placeholder="Username" required>
            <label for="inputEmail">Username</label>
        </div>

        <div class="form-label-group">
            <input name="password1" type="password" id="inputPassword1" class="form-control" placeholder="Password" required>
            <label for="inputPassword1">Password</label>
        </div>

        <div class="form-label-group">
            <input name="password2" type="password" id="inputPassword2" class="form-control" placeholder="Password" required>
            <label for="inputPassword2">Password</label>
        </div>

        <div class="checkbox mb-3 text-center">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>

        <button class="btn btn-lg btn-success btn-block" type="submit">Sign Up</button>

        <div class="login-button">
            <div class="text-center">
                    <label>Already have an account?</label>
            </div>
            <a href="{{ url_for('login.show_login') }}">
                <button class="btn btn-lg btn-info btn-block" type="button">Log In</button>
            </a>
        </div>

        <p class="mt-5 mb-3 text-muted text-center">Copyright &copy; Matthew Muccio 2018</p>
    </form>
</body>

</html>